"use client";
import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/SideBar";
import NavBar from "./components/NavBar";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "savvytech-frontedn-task-assignment",
//   description: "Generated by Ali khodaverdi",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setisMenuOpen] = useState(false);

  return (
    <html lang="fa">
      <body>
        <div className="bg-gray-500 h-screen">
          <NavBar />
          <div className="flex bg-amber-400 w-full h-[95%]">
            <aside
              className={`bg-red-400 duration-200 transition-all ${
                isMenuOpen ? "overflow-hidden w-[5%]" : "w-[10%]"
              }`}
            >
              <SideBar isMEnuOpen={isMenuOpen} setisMenuOpen={setisMenuOpen} />
            </aside>
            <main
              className={`bg-yellow-400   ${
                isMenuOpen ? "overflow-hidden w-[95%] p-2" : "w-[90%] p-3"
              }`}
            >
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
