import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "savvytech-frontedn-task-assignment",
  description: "Generated by Ali khodaverdi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <div className="bg-gray-500 h-screen">
          <nav className="bg-green-400 h-[5%]">navbar</nav>
          <div className="flex bg-amber-400 w-full h-[95%]">
            <aside className="bg-red-400 w-[10%]">
              <SideBar />
            </aside>
            <main className="bg-yellow-400 w-[90%]">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
