import { ProductType } from "../types/types";

// Data generated by AI

export const products: ProductType[] = [
  {
    id: "1",
    title: "MacBook Pro 16 M3",
    desc: "High-performance laptop for developers and designers.",
    price: 3200,
    date: new Date(),
  },
  {
    id: "2",
    title: "Dell XPS 13",
    desc: "Lightweight and premium ultrabook for everyday work.",
    price: 1800,
    date: new Date(),
  },
  {
    id: "3",
    title: "Lenovo ThinkPad X1 Carbon",
    desc: "Durable and reliable laptop loved by developers.",
    price: 2000,
    date: new Date(),
  },
  {
    id: "4",
    title: "ASUS ROG Strix G16",
    desc: "Powerful gaming laptop with excellent cooling.",
    price: 2500,
    date: new Date(),
  },
  {
    id: "5",
    title: "HP Spectre x360",
    desc: "Convertible premium laptop for students and designers.",
    price: 1700,
    date: new Date(),
  },
  {
    id: "6",
    title: "Acer Predator Helios",
    desc: "Aggressive performance for high-end gaming.",
    price: 2200,
    date: new Date(),
  },
  {
    id: "7",
    title: "Microsoft Surface Laptop 5",
    desc: "Clean Windows experience with a minimalist design.",
    price: 1600,
    date: new Date(),
  },
  {
    id: "8",
    title: "Razer Blade 15",
    desc: "Luxury gaming laptop with a sleek build.",
    price: 2800,
    date: new Date(),
  },
  {
    id: "9",
    title: "Samsung Galaxy Book3 Ultra",
    desc: "Super lightweight laptop with a stunning display.",
    price: 2100,
    date: new Date(),
  },
  {
    id: "10",
    title: "LG Gram 17",
    desc: "Extremely light laptop with a large display.",
    price: 1900,
    date: new Date(),
  },
];
